# Generated by Django 4.1.5 on 2023-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo: *')),
                ('password', models.CharField(max_length=8, verbose_name='Contraseña: *')),
            ],
        ),
    ]
