# Generated by Django 4.1.5 on 2023-02-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
