# Generated by Django 4.1.5 on 2023-01-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
