# Generated by Django 4.1.5 on 2023-02-03 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
