# Generated by Django 4.1.5 on 2023-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='@', max_length=255, verbose_name='Correo: *'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='@', max_length=8, verbose_name='Contraseña: *'),
        ),
    ]
